image:
    file: .gitpod.Dockerfile

tasks:
    - name: Restore & Build
      init: |
          cd CalcStats
          dotnet dev-certs https 
          dotnet restore
          dotnet build

vscode:
    extensions:
        - muhammad-sammy.csharp
